const COMPARISON_EQUAL = '=';
const COMPARISON_GREATER_THAN = '>';
const COMPARISON_LESS_THAN = '<';
const COMPARISON_GREATER_OR_EQUAL = '>=';
const COMPARISON_LESS_OR_EQUAL = '<=';
const COMPARISON_BETWEEN = 'between';

module.exports = {
    COMPARISON_EQUAL,
    COMPARISON_GREATER_THAN,
    COMPARISON_LESS_THAN,
    COMPARISON_GREATER_OR_EQUAL,
    COMPARISON_LESS_OR_EQUAL,
    COMPARISON_BETWEEN,
};