const COMPARISONS = require('../DatabaseSuport/EnumComparison');

const FILTER_FIELDS = {
    numberPeople: [
        COMPARISONS.COMPARISON_EQUAL, 
        COMPARISONS.COMPARISON_GREATER_THAN, 
        COMPARISONS.COMPARISON_LESS_THAN, 
        COMPARISONS.COMPARISON_GREATER_THAN_OR_EQUAL, 
        COMPARISONS.COMPARISON_LESS_THAN_OR_EQUAL, 
        COMPARISONS.COMPARISON_BETWEEN
    ],
    numberAnimals: [
        COMPARISONS.COMPARISON_EQUAL, 
        COMPARISONS.COMPARISON_GREATER_THAN, 
        COMPARISONS.COMPARISON_LESS_THAN, 
        COMPARISONS.COMPARISON_GREATER_THAN_OR_EQUAL, 
        COMPARISONS.COMPARISON_LESS_THAN_OR_EQUAL, 
        COMPARISONS.COMPARISON_BETWEEN
    ],        
    dateHour: [
        COMPARISONS.COMPARISON_EQUAL, 
        COMPARISONS.COMPARISON_GREATER_THAN, 
        COMPARISONS.COMPARISON_LESS_THAN, 
        COMPARISONS.COMPARISON_GREATER_THAN_OR_EQUAL, 
        COMPARISONS.COMPARISON_LESS_THAN_OR_EQUAL, 
        COMPARISONS.COMPARISON_BETWEEN
    ],
    idStatus: [
        COMPARISONS.COMPARISON_EQUAL
    ]
};

module.exports = FILTER_FIELDS;